### ISSUE TITLE
Running eslint with this rule in gulp return `Error: Cannot find module 'package.json'`

### ISSUE THREAD

**Issue by ohardy** [mysticatea/eslint-plugin-node#1]
Looks like in `get-package-json.js`:

```
startPath = 'gulpfile.babel.js'
path.join('.', 'package.json'); => 'package.json'
```
So it try to require 'package.json' instead of './package.json'

Sorry no time today to do a pull request :(

**Comment by mysticatea** [comment]
Thank you for this issue.

I have a plan to stop using `require` here then use `fs`.
Some editors (e.g. VSCode, Atom) execute eslint in own process, so implicit cache is a cause of a bug.

I will work on this.
