### ISSUE TITLE
Rule `node/no-unpublished-require` should ignore webpack config file

### ISSUE THREAD

**Issue by sindresorhus** [mysticatea/eslint-plugin-node#105]
I'm currently getting:

```
  webpack.config.js:3:25
  ✖    3:25  "webpack" is not published.                  node/no-unpublished-require
  ✖    4:31  "node-env-webpack-plugin" is not published.  node/no-unpublished-require
  ✖    5:28  "copy-webpack-plugin" is not published.      node/no-unpublished-require
  ✖    6:36  "clean-webpack-plugin" is not published.     node/no-unpublished-require
```

With v5.2.1

**Comment by mysticatea** [comment]
Thank you for this issue.

The `webpack.config.js` seems to publish by `npm publish` command. Do you have `files` field of `package.json` or `.npmignore` file?

> https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unpublished-require.md#rule-details

**Comment by sindresorhus** [comment]
No, I'm working on an app, not a module, so it makes no sense to use `files` or `.npmignore`.

**Comment by mysticatea** [comment]
`node/no-unpublished-require` is a rule to prevent runtime errors (`require("foo")` imports not-published file or devDep package) after `npm publish`. If the package isn't intended to publish, I think better to disable the rule.

**Comment by mysticatea** [comment]
`node/no-missing-require` and `node/no-extraneous-require` rules will catch "Module not found" errors in local.

**Comment by sindresorhus** [comment]
I use the same config for modules and apps. I don’t see what’s wrong in the rule being a little bit smart. I rather just remove the rule from XO than turning it off manually in each app project.

**Comment by mysticatea** [comment]
The rule requires distinguishing published (production) files and dev files to work, and it's using `files` field and `.npmignore` to distinguish because those decide which files are published (production).

**Comment by mysticatea** [comment]
I won't add exceptions by file path into the rule because `.eslintrc.*` files have `overrides` config.

```json
{
    "plugins": [ ... ],
    "rules": { ... },
    "overrides": [{
        "files": ["webpack.config.js", "test/**/*.js"],
        "rules": {
            "node/no-unpublished-require": "off"
        }
    }]
}
```

**Comment by sindresorhus** [comment]
That still requires specifying it manually.

**Comment by sholladay** [comment]
@sindresorhus I think you should reconsider not using `files` in your app. If for no other reason than to document which files are intended for production.

It's also functional in many cases, even for apps. For example, everything I deploy to [now.sh](https://zeit.co/now) uses `files` and they automatically figure out what to deploy based on that, which is awesome. Among other things, this ensures my `.env` files with secret keys don't get leaked to their cloud unencrypted. This is a huge deal for me, because on their OSS plan, they provide a `/_src` route to view the deployed code.
