### ISSUE TITLE
[request] no-unsupported-features supports Node.js APIs other than ES features

### ISSUE THREAD

**Issue by teppeis** [mysticatea/eslint-plugin-node#118]
Currently `no-unsupported-features` only supports ES features.
Moreover, I think that it's wonderful if the Node API is also supported.

For example
- new globals: `URL`, `URLSearchParams` (since v10.0)
- new modules: `require('http2')` (since v8.4)
- new module path: `require('fs/promises')` (since v10.0)
- new module methods: `fs.copyFile`, `fs.copyFileSync` (since v8.5)
- new module props: `require('assert').strict` (since v10.0)

I guess it's difficult to detect methods or props, but not impossible only for main case.

**Comment by mysticatea** [comment]
Thank you for this issue.

Yes, this plugin should detect those. I have a plan to separate `no-unsupported-features` rule to `no-unsupported-ecma-features` and `no-unsupported-node-features` rules.

**Comment by teppeis** [comment]
Great!

**Comment by teppeis** [comment]
Thank you!
