### ISSUE TITLE
Allow to pass a version range to `no-unsupported-features`'s `version` option 

### ISSUE THREAD

**Issue by pvdlg** [mysticatea/eslint-plugin-node#119]
The [no-unsupported-features](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unsupported-features.md) rules allow to set the Node version with either the `engines` field in the `package.json` or the [`version` option](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unsupported-features.md#version).

If set via the `engines` field in the `package.json` a version range is allowed (for example `>=4`) however it seems only version number are allowed for the [`version` option](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unsupported-features.md#version).

It would be more intuitive to handle the value of `version` option the same way as  the  `engines.node` in `package.json` and allow either a range or a version for both.

**Comment by mysticatea** [comment]
Thank you for this issue and I apologize for the delay.

I published `7.0.0` and now it supports the range notation.
(note: the `no-unsupported-features` rule was deprecated and replaced by `no-unsupported-features/es-builtins` and `no-unsupported-features/es-syntax` rules.)
