### ISSUE TITLE
Test against ESLint 5

### ISSUE THREAD

**Issue by edmorley** [mysticatea/eslint-plugin-node#125]
Hi!

It would be great to add ESLint 5 to the test matrix here:
https://github.com/mysticatea/eslint-plugin-node/blob/e957849ce0691794741fb793cab0e61090773340/.travis.yml#L9-L10

**Comment by mysticatea** [comment]
Thank you for this issue. I'm sorry for the delay.

I added!

**Comment by edmorley** [comment]
Many thanks :-)
