### ISSUE TITLE
node/no-unpublished-require incorrectly thinks file is published

### ISSUE THREAD

**Issue by jaydenseric** [mysticatea/eslint-plugin-node#126]
In this situation…

```
.
├── package.json
├── test.js
└── lib
    └── test.js
```

`package.json`:

```json
{
  "files": [
    "lib",
    "!test.js"
  ],
  "devDependencies": {
    "tap": "*"
  }
}
```

In `./test.js`:

```js
// Correctly no node/no-unpublished-require error.
const tap = require('tap')
```

In `./lib/test.js`:

```js
// Incorrectly has node/no-unpublished-require error!
const tap = require('tap')
```

The `node/no-unpublished-require error` rule incorrectly thinks that `./lib/test.js` is published, causing the error. It does not seem to understand that negated globs apply recursively to files. `!test.js` prevents the file from being published in the nested files/folders; testable by running `npm pack`.

**Comment by XhmikosR** [comment]
I'm also hitting a similar issue, I think it's the same though.

I have a file in `bin/foo.js`. The files property lists this explicitly and there's no .npmignore file.

https://travis-ci.org/css/csso-cli/jobs/472377577#L465

@mysticatea: any chance we could get this fixed?

**Comment by pke** [comment]
Even with the fix I am still getting this error when requiring the most recent "tap" version `"tap": "14.8.2"`
