### ISSUE TITLE
Ignore node features rule only for some files

### ISSUE THREAD

**Issue by lirantal** [mysticatea/eslint-plugin-node#128]
The `node/no-unsupported-features` rule is quite useful but usually while you want to keep a published npm module compatible with old Node.js versions, you'd still want to write tests using newer language and Node.js runtime features.

Is it possible to use this rule but to tell it to ignore specific paths?
Looks like the ignore option is only for ignoring language syntax.

**Comment by mysticatea** [comment]
Yes, please use the `overrides` feature.

**Comment by lirantal** [comment]
I didn't know about this one, thanks!
