### ISSUE TITLE
no-unsupported-features replaced by some other rules

### ISSUE THREAD

**Issue by Aladdin-ADD** [mysticatea/eslint-plugin-node#129]
~~another way is keep the old rules, but adding `replacedBy` field in meta (just like eslint does)~~

it's not documented.

**Comment by openjck** [comment]
Is `no-unsupported-features` no longer respected? The following line appears to be ignored in my configuration:

```javascript
        'node/no-unsupported-features': ['error', {ignores: ['modules']}],
```

**Comment by mysticatea** [comment]
> it's not documented.

Oh, I have forgotten it.
[Release note](https://github.com/mysticatea/eslint-plugin-node/releases/tag/v7.0.0) mentioned.

>Is node/no-unsupported-features now ignored? 

No. That rule is still working.

![image](https://user-images.githubusercontent.com/1937871/42855503-cbe5b148-8a7b-11e8-97ef-e3d2be2454af.png)

But that rule will never be updated, so please switch to `node/no-unsupported-features/es-syntax` and `node/no-unsupported-features/es-builtins` rules.
