### ISSUE TITLE
Set a default engine version unless specified by package.json

### ISSUE THREAD

**Issue by kclonts** [mysticatea/eslint-plugin-node#137]
How can we set a default engine version _inside of the eslintrc.json_ when using a generic styling guide over a range of projects?

Thanks! if there's no easy way someone knows to add, I can take a look and make a PR

**Comment by kclonts** [comment]
Found the solution I think, putting this in rules

{
    "node/no-unsupported-features/es-syntax": ["error", {
        "version": ">=6.0.0",
        "ignores": []
    }]
}

as per the docs from https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unsupported-features/es-syntax.md

I don't know if any other rules looks at the node version however. I'll keep this open unless someone knows for sure

**Comment by mysticatea** [comment]
I'm sorry for overlooking this issue. I had been in the hospital at that time.

Yes, you can use `version` option to specify it in `.eslintrc.*` files. The three `node/no-unsupported-features/*` rules have the option.
