### ISSUE TITLE
Import and export declarations are not supported yet.

### ISSUE THREAD

**Issue by jinxac** [mysticatea/eslint-plugin-node#140]
I am using eslint with react-native and getting following error with import/export statement. Can someone please help?

**Comment by mysticatea** [comment]
That looks not an issue of this plugin.

See the official documentation of ESLint: https://eslint.org/docs/user-guide/configuring
Use forum such as stackoverflow.com or [gitter.im](https://gitter.im/eslint/eslint).

**Comment by tafelnl** [comment]
@mysticatea 

This error is also shown when using in combination with eslint-babel. Babel let's you use import and export statements in a Node.js environment.

Is it an idea to be able to ignore this warning?
