### ISSUE TITLE
Readme doesn't instruct to add this package to the plugins field of .eslintrc

### ISSUE THREAD

**Issue by marcospgp** [mysticatea/eslint-plugin-node#152]
Is this really unnecessary? So far all plugins I've seen require this.

**Comment by mysticatea** [comment]
Yes.

**Comment by marcospgp** [comment]
Just to be clear then, what makes this plugin not need to be declared in
that field?

**Comment by mysticatea** [comment]
Because `node/recommended` includes it. Most plugins are same.
