### ISSUE TITLE
VSCode ESLint error: The "path" argument must be of type string. Received type undefined 

### ISSUE THREAD

**Issue by dwightjack** [mysticatea/eslint-plugin-node#163]
Hi, 

I'm getting the error in the title in VSCode.

My current setup: 

- VSCode 1.33.1 
- ESLint extension 1.8.2
- ESLint 5.15.1
- eslint-plugin-node 9.0.1
- node 10.13.0

Eslint config:

```json
{
  "extends": ["eslint:recommended", "plugin:node/recommended", "prettier"],
  "env": {
    "node": true
  },
  "plugins": ["node", "prettier"],
  "parserOptions": {
    "ecmaVersion": 2018
  },
  "rules": {
    "no-console": 0,
    "node/no-unpublished-require": 0,
    "prettier/prettier": ["error"]
  }
}
```

Using the output console I've tracked the problem to this line https://github.com/mysticatea/eslint-plugin-node/blob/v9.0.1/lib/configs/recommended.js#L8 but the code looks fine to me. Any hint on how to investigate the problem?

**Comment by mysticatea** [comment]
Did you run "Reload Window" command (or restart VSCode) after `npm install`? The part of old `eslint-plugin-node` might remain in VSCode memory.

**Comment by dwightjack** [comment]
@mysticatea You're right. Reloading VSCode fixed the issue. 

Sorry I didn't check it out before opening an issue!
