### ISSUE TITLE
`no-unsupported-features/node-builtins` for experimental

### ISSUE THREAD

**Issue by brettz9** [mysticatea/eslint-plugin-node#166]
Can you enable an option or rule to enforce `node/no-unsupported-features/node-builtins` but allowing for use of experimental features?

**Comment by mysticatea** [comment]
There is [`ignores` option](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unsupported-features/node-builtins.md#options).

**Comment by brettz9** [comment]
I guess that works :)

**Comment by brettz9** [comment]
I guess that works... Thanks!
