### ISSUE TITLE
Rule request: no-missing-dependency

### ISSUE THREAD

**Issue by bjrmatos** [mysticatea/eslint-plugin-node#17]
The idea of this rule is to disallow require/import of a dependency not listed explicitly in `package.json`.

The rule would be useful when using npm 3, since npm 3 auto-dedupes and dependencies get installed in a flat form. the app have the posibility to require a module that is not a explicit dependency, this rule would prevent that scenario

Thoughts?

**Comment by bjrmatos** [comment]
The rule could be named `no-missing-dependency-require`,`no-missing-dependency-import`

**Comment by mysticatea** [comment]
Thank you for this issue.

I think `no-unpublished-*` rules are it.
Could you confirm?

**Comment by bjrmatos** [comment]
sorry for the delay, you're right `no-unpublished-*` rules cover that scenario!
