### ISSUE TITLE
Adopt no-callback-literal rule

### ISSUE THREAD

**Issue by feross** [mysticatea/eslint-plugin-node#178]
Hi there!

I'd like to deprecate `eslint-plugin-standard`. We currently have four rules, three of which are no longer used by us since ESLint core now has suitable alternatives built-in.

The fourth rule is quite useful.

`no-callback-literal` - Ensures the Node.js error-first callback pattern is followed. Specifically, when a function is named `cb` or `callback`, then it must be called with `undefined`, `null` or an `Error` object as the first function argument.

```js
// okay
cb(undefined)
cb(null, 5)
callback(new Error('some error'))
callback(someVariable)

// error
cb('this is an error string')
cb({ a: 1 })
callback(0)
```

We have code and tests for the implementation (https://github.com/standard/eslint-plugin-standard/blob/master/rules/no-callback-literal.js).

Ideally, we'd be able to just deprecate `eslint-plugin-standard` since we're currently maintaining a whole ESLint plugin just for a single rule.

So, my question is – would `eslint-plugin-node` like to adopt this rule? It seems like a good fit. Let me know what you think!

**Comment by feross** [comment]
I should note that the rule has one bug that we are aware of. We falsely report an error when the spread operator is used. This is probably an easy fix.

```js
function a (cb) {
  cb(...[new Error(''), 1, 2]) // Unexpected literal in error position of callback.
}
```

**Comment by mysticatea** [comment]
I'm fine if this plugin hosts that rule. But I'm not sure if `plugin:node/recommended` will not include the rule because of false positive.

**Comment by feross** [comment]
@mysticatea Great! I sent a PR: https://github.com/mysticatea/eslint-plugin-node/pull/179
