### ISSUE TITLE
Separate static method linting from no-unsupported-features rule

### ISSUE THREAD

**Issue by AprilArcus** [mysticatea/eslint-plugin-node#18]
It would be cool to be able to lint against inappropriate use of unsupported static methods separately from the other unsupported syntax features when using e.g. Babel without the polyfill and targeting older versions of node.

**Comment by mysticatea** [comment]
Interesting.

Indeed, the kinds of `"ignores"` option of static methods are so many.

How about adding grouping values of `"ignores"` option?
e.g. `Object.*`, `Array.*`, `staticMethods`, `globalVariables`, `syntax`, etc...

**Comment by AprilArcus** [comment]
While that would accomplish the same end, I still think it would be more straightforward to have separate `no-unsupported-syntax` and `no-unsupported-methods` rules.

**Comment by AprilArcus** [comment]
That would be great :)

**Comment by mysticatea** [comment]
OK, I'm thinking like below:

- `"syntax"`
  - `"defaultParameters"`
  - `"restParameters"`
  - `"spreadOperators"`
  - `"objectLiteralExtensions"`
  - `"forOf"`
  - `"binaryNumberLiterals"`
  - `"octalNumberLiterals"`
  - `"templateStrings"`
  - `"regexpY"`
  - `"regexpU"`
  - `"destructuring"`
  - `"unicodeCodePointEscapes"`
  - `"new.target"`
  - `"const"`
  - `"let"`
  - `"blockScopedFunctions"`
  - `"arrowFunctions"`
  - `"generatorFunctions"`
  - `"classes"`
  - `"modules"`
- `"runtime"`
  - `"globalObjects"`
    - `"typedArrays"`
      - `"Int8Array"`
      - `"Uint8Array"`
      - `"Uint8ClampedArray"`
      - `"Int16Array"`
      - `"Uint16Array"`
      - `"Int32Array"`
      - `"Uint32Array"`
      - `"Float32Array"`
      - `"Float64Array"`
      - `"DataView"`
    - `"Map"`
    - `"Set"`
    - `"WeakMap"`
    - `"WeakSet"`
    - `"Proxy"`
    - `"Reflect"`
    - `"Promise"`
    - `"Symbol"`
  - `"staticMethods"`
    - `"Object.*"`
      - `"Object.assign"`
      - `"Object.is"`
      - `"Object.getOwnPropertySymbols"`
      - `"Object.setPrototypeOf"`
    - `"String.*"`
      - `"String.raw"`
      - `"String.fromCodePoint"`
    - `"Array.*"`
      - `"Array.from"`
      - `"Array.of"`
    - `"Number.*"`
      - `"Number.isFinite"`
      - `"Number.isInteger"`
      - `"Number.isSafeInteger"`
      - `"Number.isNaN"`
      - `"Number.EPSILON"`
      - `"Number.MIN_SAFE_INTEGER"`
      - `"Number.MAX_SAFE_INTEGER"`
    - `"Math.*"`
      - `"Math.clz32"`
      - `"Math.imul"`
      - `"Math.sign"`
      - `"Math.log10"`
      - `"Math.log2"`
      - `"Math.log1p"`
      - `"Math.expm1"`
      - `"Math.cosh"`
      - `"Math.sinh"`
      - `"Math.tanh"`
      - `"Math.acosh"`
      - `"Math.asinh"`
      - `"Math.atanh"`
      - `"Math.trunc"`
      - `"Math.fround"`
      - `"Math.cbrt"`
      - `"Math.hypot"`
    - `"Symbol.*"`
      - `"Symbol.hasInstance"`
      - `"Symbol.isConcatSpreadablec"`
      - `"Symbol.iterator"`
      - `"Symbol.species"`
      - `"Symbol.replace"`
      - `"Symbol.search"`
      - `"Symbol.split"`
      - `"Symbol.match"`
      - `"Symbol.toPrimitive"`
      - `"Symbol.toStringTag"`
      - `"Symbol.unscopables"`
  - `"extends"`
    - `"extendsArray"`
    - `"extendsRegExp"`
    - `"extendsFunction"`
    - `"extendsPromise"`
    - `"extendsBoolean"`
    - `"extendsNumber"`
    - `"extendsString"`
    - `"extendsMap"`
    - `"extendsSet"`
