### ISSUE TITLE
eslint-utils dependency vulnerability

### ISSUE THREAD

**Issue by remidenele** [mysticatea/eslint-plugin-node#180]
[eslint-utils has a vulnerability](https://github.com/mysticatea/eslint-utils/security/advisories/GHSA-3gx7-xhv7-5mx3) in versions **>= 1.2.0, < 1.4.1**

![image](https://user-images.githubusercontent.com/8693949/63752455-8fde7c00-c8b1-11e9-8114-bf8c5ddd507f.png)

Can you update the version of the the eslint-utils dependency from 1.3.1 to at least 1.4.1 in [package.json](https://github.com/mysticatea/eslint-plugin-node/blob/master/package.json#L17) to fix it?

**Comment by talr1** [comment]
Can you release a new version with this fix?

thanks
