### ISSUE TITLE
Can we ignore `require.resolve` in `try/catch` block for rule `node/no-extraneous-require`?

### ISSUE THREAD

**Issue by JounQin** [mysticatea/eslint-plugin-node#185]

**Comment by mysticatea** [comment]
Just out of curiosity, why do you want to ignore that in `try` statements? If the path is not static, the rule ignores it already. I'm not sure why you want to do with conditional way for static stuff.

**Comment by JounQin** [comment]
I want to detect whether the package exists and resolve different configurations.

**Comment by JounQin** [comment]
Example: https://github.com/rx-ts/eslint-mdx/blob/master/packages/eslint-plugin-mdx/src/rules/helper.ts#L66

**Comment by mysticatea** [comment]
Thank you. But I'm still not understanding why the statement is needed. How does the extraneous package come? It looks fragile approach, e.g. people may have the package for another reason from the assumption of your package.

Anyway, all `try` statements are not for `require.resolve` and it's hard to distinguish `try` statements for `require.resolve` or not. And it looks rare cases, I don't see enough pros to implement it.

**Comment by JounQin** [comment]
That OK, I'm just sharing my thoughts here.

And another example could be shareable configurations like https://github.com/1stG/configs/blob/master/packages/eslint-config/overrides.js#L11. I'm trying to simplify our configuration usage in different projects with fallback preset. I don't know is that a common pattern.

**Comment by JounQin** [comment]
close for now, disable the rule inline case by case is fine enough.
