### ISSUE TITLE
Legacy assert is not deprecated anymore

### ISSUE THREAD

**Issue by gabegorelick** [mysticatea/eslint-plugin-node#188]
The legacy assert APIs were un-deprecated in https://github.com/nodejs/node/pull/28892 which was released as part of 12.8.0.

**Comment by dylanlingelbach** [comment]
This appears to be fixed in version 11.0.0

**Comment by gabegorelick** [comment]
> This appears to be fixed in version 11.0.0

Specifically, https://github.com/mysticatea/eslint-plugin-node/commit/276a9ad0fa8d6db224aae6fe6d35146a3fac9377.
