### ISSUE TITLE
no-unsupported-features/node-builtins reports false positive for backported feature when using >=

### ISSUE THREAD

**Issue by gabegorelick** [mysticatea/eslint-plugin-node#212]
`no-unsupported-features/node-builtins` flags usages of `fs.promises` with the following error: `The 'fs.promises' is not supported until Node.js 11.14.0 (backported: ^10.17.0). The configured version range is '>=10.17.0'`.

However, I have `"node": ">=10.17.0"` in my `engines` field.  Switching to `^10.17.0` fixes this, but it shouldn't be necessary.

`>=10.17.0 || ^10.17.0` doesn't work either.

**Comment by gabegorelick** [comment]
I think this is working as expected. Assuming the data in this repo is correct, then `fs.promises` was added in 10.17.0 and 11.14.0. But  `>=10.17.0` can match a version like 11.0.0. Likewise, `>=10.17.0 || ^10.17.0` can also match 11.0.0. Thus you can potentially have a version that does not support this feature. 

I think what I should use instead is something like `^10.17.0 || >=11.14.0`.

**Comment by jaydenseric** [comment]
Thanks for sharing your realization, it really helped me too!
