### ISSUE TITLE
`no-missing-require` doesn't work in Atom (linter-eslint)

### ISSUE THREAD

**Issue by teppeis** [mysticatea/eslint-plugin-node#28]
In Atom with linter-eslint, `no-missing-require` always reports an error `"x" is not found` for npm packages and local files. Passed for core modules. 

<img width="664" alt="cli_js_ __users_teppeis_workspace_fixclosure" src="https://cloud.githubusercontent.com/assets/26476/14061285/b6fc283e-f3bf-11e5-873c-75c49e10cee7.png">

All versions are latest stable:
- Mac OS X 10.11.4
- Atom v1.6.0
- ESLint v2.5.1
- linter v1.11.1
- linter-eslint v7.1.3

**Comment by mysticatea** [comment]
Thank you for this issue.

Hmm, I saw a different behavior in my environment.
Modules are OK but file paths are reported wrongly.
It was working fine until ESLint v2.4.0.

- Windows 7 64bit
- Atom v1.6.0
- ESLint v2.5.1
- linter v1.11.4
- linter-eslint v7.1.3

![image](https://cloud.githubusercontent.com/assets/1937871/14065088/399edc1e-f456-11e5-96f1-6e364c242ef6.png)

I will investigate this.

**Comment by mysticatea** [comment]
Hmm, `context.getFilename()` of ESLint API seems to return wrong path.
I peeked `eslint.CLIEngine#executeOnText`, and I received a wrong path from Atom.
I'm still digging.

**Comment by mysticatea** [comment]
OK. I'm pretty sure this is a spec of Atom's `linter-eslint`.

Atom's `linter-eslint` gives file names instead of file paths by default.
When a `.eslintignore` file exists, Atom's `linter-eslint` gives relative paths from `.eslintignore`.

So you have to make `.eslintignore` file onto the project root directory to use `node/no-missing-require` rule on Atom.

**Comment by mysticatea** [comment]
Wait.
I found a huge side effect in `getRelativePath` of Atom's `linter-eslint`: https://github.com/AtomLinter/linter-eslint/blob/977fe57693e23b4bd664673496f4d6509518bbfb/src/worker-helpers.js#L103

**Comment by mysticatea** [comment]
Ultimately, this is a bug of ESLint.
Please track https://github.com/eslint/eslint/issues/5694.

As a workaround, you can avoid this issue for now if you make `.eslintignore` onto the project root.

**Comment by teppeis** [comment]
@mysticatea thanks for nice dig!
