### ISSUE TITLE
Last commit:  Jun 9, 2020

### ISSUE THREAD

**Issue by thernstig** [mysticatea/eslint-plugin-node#281]
I absolutely do not like creating a thread like this and understand if it is immediately closed.

Last commit was almost a year ago now; Jun 9, 2020. Several pull requests are in the pipe. But there is no maintainer activity in issue nor in pull requests for quite some time.

Is the plugin considered stable enough or is there other reasons no maintainers are very active here anymore?

**Comment by sosukesuzuki** [comment]
This project needs to continue to be maintained as Node.js evolves.
I had a private chat with @mysticatea. He currently doesn't have enough time for OSS maintenance. So I'm going to help him with the maintenance of this project. But sorry there are no concrete plans for the next release for now.

**Comment by cincodenada** [comment]
Thank you for your work here @sosukesuzuki - your latest commits have addressed exactly what I came here looking for, which was closing the gap between ES2020 and Node 12. I think those are worth a release in and of themselves, but I understand that releases are complicated, so I trust that it'll happen if/when it's ready.

**Comment by thernstig** [comment]
@sosukesuzuki I noticed you started doing some commits, but later it stopped. Is it maybe true that you need to create an issue (pin it) and ask for more core maintainers?

**Comment by dhurlburtusa** [comment]
It would be nice if the changes from https://github.com/mysticatea/eslint-plugin-node/commit/c4a37a6635317088ea8583d2dd512942e8ca2425#diff-e5b43c774c89958b1fa6ab3bb43f30615166d3bc786cbada6a8269093940b854 could be released soon. I had to find out the hard way that optional chaining wasn't supported in the versions of node we run CI with.
