### ISSUE TITLE
Read required Node.js version from project package.json

### ISSUE THREAD

**Issue by sindresorhus** [mysticatea/eslint-plugin-node#29]
For the `no-unsupported-features` rule. I have a shareable config and I don't want to manually specify the required Node.js version for each project. That information is already available in the `engines` field in package.json.

You could use [`read-pkg-up`](https://github.com/sindresorhus/read-pkg-up).

**Comment by mysticatea** [comment]
Thank you for this issue.

It's a good idea!
I will make the rule reading that information by default.

**Comment by mysticatea** [comment]
Hmm, [semver] seems to not provide API to get the minimum version of semver ranges. @sindresorhus Do you have any idea?

[semver]: https://www.npmjs.com/package/semver

**Comment by mysticatea** [comment]
Oh, I found.

![image](https://cloud.githubusercontent.com/assets/1937871/14850760/32be08ca-0cb6-11e6-9f61-ddaa49a06ad3.png)
