### ISSUE TITLE
Rule node/no-missing-import is not compatible with typescript import with .js suffix

### ISSUE THREAD

**Issue by fupengl** [mysticatea/eslint-plugin-node#342]
"eslint": "^8.23.1",
    "eslint-import-resolver-typescript": "^3.5.1"
    "eslint-plugin-import": "^2.26.0",

<img width="265" alt="image" src="https://user-images.githubusercontent.com/20211964/190865985-b7ff8569-83d8-433f-854b-8c19753abf7e.png">
This import is legal, but it is not compatible with this way of writing ts

**Comment by siva-444** [comment]
+1

**Comment by fupengl** [comment]
tsconfig.json
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "nodenext"
  }
}

```

Configuring `moduleResolution` as `node` can solve this problem
