### ISSUE TITLE
Provide the config plugin:node/recommended

### ISSUE THREAD

**Issue by rkaneko** [mysticatea/eslint-plugin-node#38]
### The version of ESLint you are using.

+ 2.12.0

### The problem you want to solve.

+ To provide the choice of the configuration by oneself or the default recommended.

### Your take on the correct solution to problem.

+ To provide the eslint-plugin-node's recommended configuration like [yannickcr/eslint-plugin-react's recommended config](https://github.com/yannickcr/eslint-plugin-react/blob/0aeebaf6d3deb318ca3437122bc575b8f1a4519e/index.js#L53-L78).

---

This issue is just a proposal.
I'd like to discuss with author @mysticatea .

Thanks.

**Comment by mysticatea** [comment]
Thank you for this issue and great PR!

I commented in the PR: #39.

**Comment by rkaneko** [comment]
:smile:

**Comment by rkaneko** [comment]
nice README!
