### ISSUE TITLE
Bug: no-deprecated-api reports invalid deprecation

### ISSUE THREAD

**Issue by danmactough** [mysticatea/eslint-plugin-node#44]
Running node v4 with the `no-deprecated-api` enabled causes the following error report:

`'Buffer' constructor was deprecated since v6. Use 'Buffer.alloc()' or 'Buffer.from()' instead  node/no-deprecated-api`

So:

- it's reporting a deprecation for a version *later* than the version I'm using
- most importantly, the alternative api *has not been implemented* in the version I'm using

This is applicable to other `Buffer` api deprecations in node 6.

By default, we should compare versions and not report that an api has been deprecated until the user is using a version in which the api has actually been deprecated. (I think it's a good idea to enable forcing the warnings so you can test forward-compatibility, though.)

**Comment by mysticatea** [comment]
Thank you for this issue.

It's intentional.

- The goal of the rule is to prevent a use of API which is going to be removed.
  A use of such API would break your software in future.
- There are reasons for deprecation of existing APIs. 
  Probably the reason is valid in old versions.
  Especially, in `Buffer` case, it has a risk of security, so I think there is worth to disallow `Buffer` constructor.

You can use [safe-buffer](https://www.npmjs.com/package/safe-buffer) instead.
Or you should write `eslint-disable` comment with the reason that the use of `Buffer` constructor is safe.

**Comment by danmactough** [comment]
I understand this was intentional. I think it's wrong. Here's the developer experience you've created:

- project uses node 4, the most current lts
- project uses the only core API available to it
- project adds your dependency with recommended settings
- eslint now fails with errors that are not actually errors

I'm sorry but that is not helpful. If I weren't up to speed on the changes to the Buffer API, I would have been completely confused.

This doesn't adhere to the principle of least surprise.

**Comment by danmactough** [comment]
Oh, but most importantly, now my linter tells me to use invalid syntax ("Use 'Buffer.alloc()' or 'Buffer.from()' instead") instead of my perfectly valid syntax.

**Comment by mysticatea** [comment]
Thank you for your opinions.
Feel free to disable the rule.

Out of curiosity, why do you want to stop warning to a use of API which has a security risk?

**Comment by danmactough** [comment]
> why do you want to stop warning to a use of API which has a security risk

The rule is about "no deprecated apis," not security issues. I don't care _why_ the API is deprecated. I only care that it _is_ deprecated. In the version of node I am running, it ***is not*** deprecated, and the error message I get is invalid and instructs me to break my code. It's hard for me to understand the argument that a tool that is supposed to help developers write error-free code doesn't have a bug when it actually tells developers to introduce errors.

Moreover, the rule doesn't check that we're using the API in an unsafe manner. (We're not.)

**Comment by mysticatea** [comment]
Thank you for explaining.

Granted, that warning message should be improved. But I don't think changing the behavior of the rule makes sense. LTS is not meaning eternal support. That API was deprecated in Node.js. Reasons exist for the deprecation. People need careful when they use the API even if using an older version. I'd like to recommend the use of a substitute (e.g. safe-buffer), or to write comments (with the reason of safe) and `eslint-disable-line` for each use of deprecated API. It would help to maintain the software. On the other hand, if they don't maintain the software, disabling the rule is no problem.  All deprecated API will not be removed in the version.

**Comment by danmactough** [comment]
Sure, LTS doesn't mean eternal support. But Node 4 is the most current LTS. This API [is not deprecated](https://nodejs.org/dist/latest-v4.x/docs/api/buffer.html#buffer_class_buffer) for Node 4 -- only Node 6+.

**Comment by mysticatea** [comment]
It's not important.
If you will not upgrade Node, you don't need to disallow deprecated API. Those will not removed in the version. You can disable this rule.
