### ISSUE TITLE
`no-unsupported-features` "blockScopedFunctions" misbehaving?

### ISSUE THREAD

**Issue by rhys-vdw** [mysticatea/eslint-plugin-node#59]
[source](https://github.com/mysticatea/eslint-plugin-node/blob/8275cfc9ce85cce951d9d94a6fe618bd7403f7b7/lib/rules/no-unsupported-features.js#L457-L459)

I get an error from a top level function definition:

```js
// whatever.js
function whatever() { } // Block-Scoped Functions are not supported yet on Node v0.10  node/no-unsupported-features
```

**Comment by mysticatea** [comment]
Thank you for this issue.

I confirmed it, if eslintrc has `{sourceType: "module"}` setting.
I will fix it.

**Comment by rhys-vdw** [comment]
Thanks @mysticatea. 👍

**Comment by rhys-vdw** [comment]
Thanks @mysticatea, seems good. 👍
