### ISSUE TITLE
Clarify `node/no-unpublished-import` and `files` in `package.json`.

### ISSUE THREAD

**Issue by evilebottnawi** [mysticatea/eslint-plugin-node#60]
I have babel and this structure:
```shell
src/index.js - my code, which published
src/__tests__/index-test.js - file contains tests, which exclude from published
```
`index.js` compiled in `dist` directory, using command `babel src --out-dir dist --ignore /__tests__/`.

In `package.json` contains (so as not publish tests.):
```
"files": [
  "dist",
  "!**/__tests__"
],
```

But i got error if can try import packages from `devDependencies` in `src/__tests__/index-test.js`:
```shell
/path/to/packege/src/__tests__/index-test.js
  4:18  error  "ava" is not published  node/no-unpublished-import
```

I can try `convertPath` options but still getting an error. Based on the description, I like to do everything right.

**Comment by mysticatea** [comment]
Thank you for this issue.

I'm sure that `files` field of `package.json` does not support `!` syntax.

Hmm, it seems `convertPath` option to have to support `ignore` option.
I'm thinking the detail spec of the option.

**Comment by evilebottnawi** [comment]
@mysticatea thanks for answer, I would be happy to see the support `!` syntax :smile: If you need help, I can try to write PR
