### ISSUE TITLE
'no-missing-require' is case insensitive

### ISSUE THREAD

**Issue by AndrewFinlay** [mysticatea/eslint-plugin-node#68]
This currently works great on a Mac where case variations aren't important.   However on a linux box where filenames are case sensitive, this won't flag missing files.

**Comment by mysticatea** [comment]
Thank you for this issue.
Sounds reasonable to me. Case sensitive checks would be useful.

**Comment by AndrewFinlay** [comment]
Thanks for that, works perfectly

**Comment by mor-gilad** [comment]
Is there a way to have a case sensitive check when on a mac machine? 
My dev environment is mac, but our production servers are linux. I want to know there are not going to be any errors on the servers...

**Comment by mysticatea** [comment]
@mor-gilad Oh, actually, I didn't realize it since I have outsourced module lookup to [resolve](https://www.npmjs.com/package/resolve) package.
