### ISSUE TITLE
rule no-missing-require is broken with 4.2.0

### ISSUE THREAD

**Issue by mathieug** [mysticatea/eslint-plugin-node#70]
Since the update from 4.1.0 to 4.2.0, rule `no-missing-require` is broken for paths like '../../somefile'

**Comment by saikojosh** [comment]
I've noticed the same issue. Super annoying! The path definitely exists but I'm told it's incorrect. 😕

**Comment by mysticatea** [comment]
Thank you for this report, and I'm sorry.
I'll investigate it.

**Comment by mysticatea** [comment]
To make sure, which is the "broken" meaning false positive or negative?
I could not reproduce it.
Please note the `no-missing-require` rule has checked files with case sensitive since v4.2.0.

**Comment by mathieug** [comment]
Broken means the file exist but I have this error: `Error - "../../../libs/co-route" is not found. (node/no-missing-require)`

**Comment by mysticatea** [comment]
Hmm, I could not reproduce it.
Could you give me whole repro step or repository?

**Comment by mathieug** [comment]
Can you try on SublimeText with those addons installed: [SublimeLinter](https://github.com/SublimeLinter/SublimeLinter3) [SublimeLinter-eslint](https://github.com/roadhump/SublimeLinter-eslint) ?

**Comment by mathieug** [comment]
Create two files:
/test1/a.js = `module.exports = {};`
/test2/b.js = `require('../test1/a')`

**Comment by mysticatea** [comment]
OK, I reproduced it on Sublime Text. Thank you!

**Comment by mathieug** [comment]
Thank **you**!

**Comment by mathieug** [comment]
Amazing, thanks @mysticatea

**Comment by mysticatea** [comment]
I released [v4.2.1](https://github.com/mysticatea/eslint-plugin-node/releases/tag/v4.2.1). I'm sorry for this annoying.

**Comment by mathieug** [comment]
Don't be.
I've tested and it works, thanks for your work and your great reactivity.

**Comment by saikojosh** [comment]
Thanks guys this works perfectly now! 😆 🎉
