### ISSUE TITLE
Better error message for switching to userlad module after Node deprecation no-deprecated-api

### ISSUE THREAD

**Issue by corbinu** [mysticatea/eslint-plugin-node#72]
So I added the punycode module to fix the fact that it is deprecated in Node v7 but I still get the error

```
error  'punycode' module was deprecated since v7. Use 'https://www.npmjs.com/package/punycode' instead  node/no-deprecated-api
```

**Comment by mysticatea** [comment]
Thank you for this issue.

However, third party modules don't hide core modules, so you are still using the deprecated core module.
See also: #69

**Comment by corbinu** [comment]
Ok thanks I changed the issue accordingly ... though I am still wondering if it is technically an error given that let's say Node v9 drops punycode. Now that I have added it to the deps my app should just keep working. For some that may be the expected behavior. However I think documenting the need for the trailing slash works too
