### ISSUE TITLE
no-unpublished-require mistakenly assumes readme.* is published even if in subdirectory

### ISSUE THREAD

**Issue by platinumazure** [mysticatea/eslint-plugin-node#73]
I'm trying to consume eslint-plugin-node in my [eslint-plugin-qunit](https://github.com/platinumazure/eslint-plugin/qunit). Unfortunately, I'm getting a false positive in rule `node/no-unpublished-require` because it mistakenly assumes a `tests/readme.js` file is going to be published by npm, and thus I am getting warned for some devDependencies being imported by the file. In reality, that file is not published (it is not among the `files` in package.json and npm's exceptions only apply to the package's top-level directory).

I think this can be fixed [here](https://github.com/mysticatea/eslint-plugin-node/blob/ba283dfb07f6b2113a8c5eea39e4d9b88e7df068/lib/util/get-npmignore.js#L73-L82) by doing one of the following:
* Pass the full relative path (from the package root directory) to the `NEVER_IGNORED` regex
* Adding a check that the file is in the package root before using the regex

I'm happy to submit a PR if needed; just please let me know which approach you prefer. Of course, I won't complain if you find time to fix this yourself :smile:

Thanks for reading and thanks for such a kickass plugin!

EDIT: I wrote a PR using the first approach. Let me know if I should switch approaches.

**Comment by mysticatea** [comment]
Thank you for this report and PR!

I confirmed it.
I greatly appreciate.

**Comment by platinumazure** [comment]
Thank you for merging my PR and cutting a release! Greatly appreciate the fast turnaround. :smile:
