### ISSUE TITLE
node/shebang detects line breaks?

### ISSUE THREAD

**Issue by futagoza** [mysticatea/eslint-plugin-node#75]
Why is the rule "node/shebang" looking for [unix line breaks](https://github.com/mysticatea/eslint-plugin-node/blob/master/lib/rules/shebang.js#L103)?

I've been using this module with ES2016+ source code up till now, but as soon as I switched to a Node.js v4 project, I decided to activate this rule, only to find that even though I'm on Windows, this rule expects me to use Unix line breaks just because I want to use a shebang, so I've got no choice but to turn it off for that project.

Can you either change how this rule behaves (e.g. ignore line breaks if running on windows, remove the line break detection, etc) or change the rule description or name (node/unix-shebang) so that it isn't misleading.

**Comment by mysticatea** [comment]
Thank you for this issue.

Because it will not work if there is `\r` there: http://unix.stackexchange.com/questions/108588/shebang-line-not-working-with-cr-lf

**Comment by mysticatea** [comment]
I remember an accident that a tool released from Windows then the tool didn't work by the `\r` for users. The purpose of this rule is prevent such accident.

**Comment by futagoza** [comment]
I understand that, but when working with git you can check out with lines automatically converted to your OS's default, and then commit with the original line breaks (Unix or Windows line breaks). I use this feature of  git because I use a variety of editors, including plain old Windows Notepad some times, and some OS specific tools only support the current systems line breaks (whether its an editor like Notepad or a script/tool that performs operations on files). I don't have any problems with executing shebang files because Node.js just ignores shebang lines, so that's not an issue.

What about an option to ignore line breaks: `"node/shebang": [ "error", { "ignoreLineBreaks": true } ]`
This way you can keep the default behaviour of this rule that your intended, but users can opt into ignoring the requirement of Unix line breaks.

If you still can't accept it, I suggest you change the rule name to 'node/unix-shebang' as well as its description, as like I said above, the current rule implies `Suggest correct usage of shebang`, but what it actually does is `Suggest correct usage of Unix shebang`.

**Comment by mysticatea** [comment]
I'm talking about `npm publish` from Windows. As you said, git may convert linebreaks automatically, so `npm publish` on Windows possibly cause the problem of shebang. The linebreak check is for Windows user.

**Comment by mysticatea** [comment]
If somebody assume all users are using Windows, or is using CI to publish, the option will be valuable. I welcome the PR.

**Comment by futagoza** [comment]
Oh, 🤣 . Never noticed the issue tbh until you just mentioned `npm publish` above so I google'd and found out what your were talking about above.

Now that I think about it, yea, that makes sense. Just going to go over the packages I've already released (and going to) to check for bin files 😆 

Still, you should put a note in the description for this rule to clarify what the intent is, as well as a link to the reason behind forcing Unix line breaks (maybe a link to [npm-issues/4607](https://github.com/npm/npm/issues/4607)).
