### ISSUE TITLE
Travis/Node.js v4 - Cannot find 'eslint-plugin-node'

### ISSUE THREAD

**Issue by futagoza** [mysticatea/eslint-plugin-node#76]
I seem to be having an issue on Travis with Node.js v4 only:

- Build: https://travis-ci.org/futagoza/ePEG.js/builds/219030102
- Job 1: https://travis-ci.org/futagoza/ePEG.js/jobs/219030103#L175

The build is running 5 jobs, using Node.js v4 - v7.8, but only the first job is failing.
Locally, I'm using Windows 10 x64 and Node.js v7.7.4, no issues there though.

Seems to have happended before as well ([eslint-issues/7239](https://github.com/eslint/eslint/issues/7239)) but you (@mysticatea) said that it was resolved, so most likely its not the same thing.

Funny thing is that it seems to work with Node.js v4 on my other travis builds for [eslint-config-futagozaryuu](https://github.com/futagoza/eslint-config-futagozaryuu), which is the module actually including _eslint-plugin-node_ for the node spefic configuration files, which are being used in the failing and passing jobs mentioned above.

I've racked my brain for the last hour trying to figure out what's wrong, but I'm giving up for today since it's late. Hoping you have a tip or solution for me tomorrow 😄

**Comment by mysticatea** [comment]
The version of npm which is bundled in Node 4 is 2.x (https://travis-ci.org/futagoza/ePEG.js/jobs/219030103#L147). Then npm 2 does not flatten dependencies, so ESLint cannot find plugins in configs.

The solution is that you add peerDependencies.
For example: https://github.com/mysticatea/eslint-config/blob/master/package.json#L18

**Comment by futagoza** [comment]
My configuration set has that already: [eslint-config-futagozaryuu/package.json#L29](https://github.com/futagoza/eslint-config-futagozaryuu/blob/master/package.json#L29), with eslint peerDependency set as `>= 3.17`

And the package this error is from has [eslint 3.19.0](https://github.com/futagoza/ePEG.js/blob/master/package.json#L44) as a devDependency.

**Comment by mysticatea** [comment]
Nope, add eslint-plugin-node to peerDependencies as well.

**Comment by futagoza** [comment]
That fixed it, thanks 😄 

Never used peerDependencies before `eslint-config-futagozaryuu`, but I just assumed it meant that NPM will assert those dependencies are installed, NOT install them, but I guess it's a life saver in the way NPM installs dependencies between NPM 2 and NPM 3+ 🤣
