### ISSUE TITLE
ESLint v4

### ISSUE THREAD

**Issue by KoltesDigital** [mysticatea/eslint-plugin-node#81]
Hi! Today is the official release of eslint v4.0.0. `eslint --init` can break because `eslint-plugin-node` only support eslint v3.x.

```
? How would you like to configure ESLint? Use a popular style guide
? Which style guide do you want to follow? Standard
? What format do you want your config file to be in? YAML
Local ESLint installation not found.
Installing eslint, eslint-plugin-standard, eslint-plugin-promise, eslint-config-standard
...
├─┬ eslint@4.0.0
├── UNMET PEER DEPENDENCY eslint-plugin-node@>=4.2.2
```

**Comment by mysticatea** [comment]
Thank you for this issue.

However, `eslint-plugin-node` supports ESLint v4.
Your error message means that a package requires `eslint-plugin-node@>=4.2.2` but missing. I'm not sure what is the "a package" from your error message.

**Comment by mysticatea** [comment]
[`eslint --init` looks to not install `eslint-plugin-node`](https://github.com/eslint/eslint/blob/c61194f9440981d6c858525273e5c469bdd98290/lib/config/config-initializer.js#L270) but [`standard` requires `eslint-plugin-node`](https://github.com/feross/eslint-config-standard/blob/bff0a4bb3447b90fc65a2de57be5d123842f6f69/package.json#L53). 

This is not a bug of this repo.

**Comment by KoltesDigital** [comment]
Right, thanks!

**Comment by mysticatea** [comment]
FYI: I have sent the PR to solve the problem: https://github.com/eslint/eslint/pull/8713
