### ISSUE TITLE
Pretty bug on `no-deprecated-api` rule

### ISSUE THREAD

**Issue by tunnckoCore** [mysticatea/eslint-plugin-node#87]
Maximum call stack size exceeded. https://github.com/standard/standard/issues/882 and https://github.com/standard/standard/issues/933

The whole thing is pretty weird. Because first issue ( `#882` ) is published on May 11, last Standard version is on April 14, and last version of this plugin on which Standard depend - `~4.2.2`, is on March 28. No new versions on that range.

**Comment by mysticatea** [comment]
Thank you for the report.

I confirmed it. I will fix it later.

> The whole thing is pretty weird. Because first issue ( #882 ) is published on May 11, last Standard version is on April 14, and last version of this plugin on which Standard depend - ~4.2.2, is on March 28. No new versions on that range.

At least, you are the first person which told me the issue, so I have not been aware of the issue.

**Comment by mysticatea** [comment]
I released v5.1.1 and v4.2.3 (backported).

**Comment by tunnckoCore** [comment]
@mysticatea Awesome, thanks!

> At least, you are the first person which told me the issue, so I had not been aware of the issue.

Yea, i seen that i thought finally to report it. :)
