### ISSUE TITLE
Merge import-related rules with eslint-plugin import?

### ISSUE THREAD

**Issue by j-f1** [mysticatea/eslint-plugin-node#89]
[`eslint-plugin-import`](https://github.com/benmosher/eslint-plugin-import) contains versions of your `no-extraneous-{import,require}` and `no-missing-{import,require}` rules.

Have you considered joining efforts with that project for those rules?
Additionally, have you considered moving `no-unpublished-{import,require}` to their repository?

**Comment by mysticatea** [comment]
Thank you for this issue.

No. At the time I created this plugin, I didn't know `eslint-plugin-import`. Those 2 plugins have been developed independently each other.
