### ISSUE TITLE
Update to enforce node.js core linting rules

### ISSUE THREAD

**Issue by geek** [mysticatea/eslint-plugin-node#9]
see https://github.com/nodejs/node/blob/master/.eslintrc

Since this is named `node` maybe you can update it to use the node.js core lint rules?

**Comment by mysticatea** [comment]
Thank you for this issue.

What do you expect from this plugin?
To add some rule?

**Comment by geek** [comment]
I was hoping to make an eslint-plugin-node that enforces the node core style rules.  Since this module already exists I want to check and see what you think of updating the module to use these rules.  If not, I can use eslint-plugin-nodejs as the name.

**Comment by mysticatea** [comment]
I believe this understandable name should be used for people who use Node.
I'd like to recommend you to use a name that Node users are not confused to choose a plugin.

If the rules profit to Node users, I'm happy to accept PRs.
