### ISSUE TITLE
node/no-deprecated-api reports exist deprecated

### ISSUE THREAD

**Issue by tinovyatkin** [mysticatea/eslint-plugin-node#90]
`exists` was undeprecated, but `node/no-deprecated-api` still reports it deprecated even while targetting Node 8 via `package.json` engines

**Comment by mysticatea** [comment]
Thank you for this issue.

However, it's not correct. `fs.exists` was deprecated: https://nodejs.org/api/fs.html#fs_fs_exists_path_callback
