### ISSUE TITLE
GLOBAL and root are deprecated in v6.0.0

### ISSUE THREAD

**Issue by eight04** [mysticatea/eslint-plugin-node#92]
https://github.com/nodejs/node/pull/1838
Can we have them in no-deprecated-api?

Related discussion:
https://github.com/eslint/eslint/issues/9144
https://github.com/sindresorhus/globals/issues/117

**Comment by mysticatea** [comment]
Thank you for the report.
Yes, we should update the `no-deprecated-api`. It exists in [the official deprecated API list](https://nodejs.org/api/deprecations.html#deprecations_dep0016_global_root) also, but I had overlooked it.
